### ISSUE TITLE
Pages to create

### ISSUE THREAD

**Issue by rohitvarkey** [IE-NITK/NITK-Student-Council-Website#1]
Below are a list of pages to be created along with the references mentioned.

- [x] Landing/Homepage - [WM](http://www.wm.edu/), [UTA fontworth](http://fortworth.uta.edu/)
- [x] News List with categorization - [Trinity News page](https://new.trinity.edu/news)
- [x] Individual News page
- [x] Events List / Calendar page - [Trinity Events list](https://new.trinity.edu/events), [WM events](https://events.wm.edu/calendar/upcoming/wm) , [Ashley School Calendar](http://www.ashevilleschool.org/about/calendars)
- ~~Individual Events page - [Polk Event Page](https://www.polk.edu/events/polk-state-gallery-exhibition-faculty-photography-2/)~~
- [x] Student Blog
- [x] Individual Article Page
- [x] Student Council (Anchor page for Meet the rep, Message from Presi etc)
- [x] Club Life
- [x] Message from the President
- [x] Meet the Representatives
- [x] Minutes of meetings (Replica of TBSB)
- [x] Announcements
- ~~Achievements and Agenda (optional)~~
- [x] Opportunities
- [x] Contact numbers
- [x] FAQ

**Comment by vinaymundada27** [comment]
@rohitvarkey : What do we do with the minutes of meetings page?
And difference between Student Council & meet the rep page?

**Comment by 97yogitha** [comment]
@rohitvarkey  is there a student council icon?

**Comment by rohitvarkey** [comment]
> is there a student council icon?

 I'm not sure. We'll need Ansu to comment on that.

> What do we do with the minutes of meetings page?

This page should be able to display a list of meetings conducted. The SC is making pdf of the minutes, so we can just link to that I guess. Ansu mentions to replicate the functionality on "The Beach Side Blues", which unfortunately seems to be down at the moment.

> And difference between Student Council & meet the rep page?

@vinaymundada27 Hmm. Don't think there is. Just confirm with Ansu once! Also you might want to take a look at the description provided in the requirement doc for the Meet The Rep page.
```
Meet the Representatives: Photo, Branch, Contact, Hostel address, Email id
Also links to past office bearers list and one group photo. 
These links should be available at the end of the page.
```

**Comment by 97yogitha** [comment]
@rohitvarkey  this is the template that could be used. Just change the extention to .html .
![nitk](https://cloud.githubusercontent.com/assets/8945204/12742206/9c3cc476-c9a9-11e5-82b7-20b8afb214b1.jpg)

[sample.txt](https://github.com/IE-NITK/NITK-Student-Council-Website/files/113516/sample.txt)

**Comment by rohitvarkey** [comment]
I've updated the issue checklist with only the pages that have been merged currently into master. If you are working on a page, please comment here with what page you are working on.

**Comment by harryvineeth** [comment]
I have started working on the Announcements Page

**Comment by 97yogitha** [comment]
@rohitvarkey  I think we should we can have contact numbers in cluded in the faq page instead of having a seperate page. Is that okay?

**Comment by rohitvarkey** [comment]
@97yogitha I think a separate page would be required. It's better than having to hunt through them in the FAQ section. Maybe add a link in the FAQ's to the contact page section?

**Comment by rohitvarkey** [comment]
Closing as majority of pages have been created.
