### ISSUE TITLE
Backend functionalities Required

### ISSUE THREAD

**Issue by rohitvarkey** [IE-NITK/NITK-Student-Council-Website#3]
This issue lays out a high level plan of the functionalities required. 

- [x] Login Mechanism
- [x] User types
     - [x] Admins
     - [x] Student Council Members
     - [x] Club Convenors & Sport Captains (Restricted to posting news and events.)
- [x] URL routing to pages
- [x] News
    - [x] Content storage (Title, details etc)
    - [x] Categories - Campus news, In the news, Spotlight
    - [ ] Customizable Ordering
    - [x] Pinning of Important Posts
- [x] Events
    - [x] Content storage (Title, details etc)
    - [ ] Tags
    - [x] Calendar Integration
- [x] Calendar (May require explicit support)
- [x] Articles 
    - [x] Content storage (Title, details etc)
    - [x] Author picture thumbnail
    - [x] Formatting (WYSIWIG editor Integration?)

The following require mostly just ability to be added using an Admin panel. Having them in a database makes writing templates easier. Reduces need to hard code static files.

- [x] Council member details - Photo, Branch, Contact, Hostel address, Email id
- [x] Add Minutes of meetings
- [x] Announcements
- [x] Opportunities

**Comment by rohitvarkey** [comment]
@abhijithanilkumar Don't tick off things until they are merged. :stuck_out_tongue:

**Comment by akaysh** [comment]
I think we should add details about database as well:
- [ ] Type of Database (MySQL, SQLite, etc.)
- [ ] Tables and Fields (Models)
- [ ] ER Diagram and Constraints

**Comment by rohitvarkey** [comment]
@abhijithanilkumar Can we get this list updated?

**Comment by abhijithanilkumar** [comment]
@rohitvarkey Models have been finalized as per requirements. I'll start working on the views once we merge all the pages. Otherwise we might get a lot of merge conflicts. :sweat_smile:

**Comment by rohitvarkey** [comment]
Now now. Merge conflicts are nothing to be scared of. :smile:

**Comment by abhijithanilkumar** [comment]
Not scared. But still we can reduce the number.

**Comment by rohitvarkey** [comment]
@abhijithanilkumar Do we have tag support for events? And customizable ordering is still on this list right?

**Comment by rohitvarkey** [comment]
Closing anyway as we have done enough for the first release!
